### ISSUE TITLE
Remove algorithms that no longer work

### ISSUE THREAD

**Issue by bherr2** [CIShell/cishell-plugins#2]
This includes the Facebook, Google Scholar, Flicker algorithms, but could be more.

**Comment by bherr2** [comment]
@mginda I need a compiled list of deprecated/non-functioning plugins. I'll then take it from there to remove them.

**Comment by mginda** [comment]
Load Menu:
Facebook 
	Access Token
	Facebook Mutual Friend Data
	Mutual Friends
Google Scholar Reader
	Google Citation User ID Search
Attach Citation Indices from Google Scholar
Attach Table Indices from Google Scholar
Flickr Reader
Twitter Reader

**Comment by mginda** [comment]
I would note that most of the Network vis plugins should be re-evaluated as a whole, however, they are not necessarily "non-functioning".

**Comment by bherr2** [comment]
Fixed in Sci2 v1.3
