### ISSUE TITLE
Sci2/CIShell fails to run on Java 9

### ISSUE THREAD

**Issue by bherr2** [CIShell/cishell-plugins#4]

**Comment by bherr2** [comment]
@mginda https://wiki.eclipse.org/Configure_Eclipse_for_Java_9 has instructions that might work.

**Comment by bherr2** [comment]
I was able to replicate the java 1.9 error on my machine. Sadly the link instructions didn't help.

**Comment by bherr2** [comment]
Fixed in Sci2 v1.3 by adding a Java 1.9 profile to the org.eclipse.osgi plugin.

**Comment by mginda** [comment]
Ok, this bug is fixed. I got Sci2 to run with Java 1.9 on my machine.

Two notes:
The sci2.ini does not have the standard vm memory limit fields that are described on the Sci2 wiki. Instead, the ini file shows eclipse start up calls. 

The Sci2 About information needs to be updated from 1.2 to 1.3

**Comment by katyb** [comment]
Thank you Michael.

Bruce,
When will we have a new build of + release notes for Sci2?
We should announce this to the students.
k


--
Katy Borner
Victor H. Yngve Distinguished Professor of Engineering and Information Science
Director, CI for Network Science Center, http://cns.iu.edu
Curator, Mapping Science exhibit, http://scimaps.org

ISE and ILS, School of Informatics and Computing, Indiana University
Luddy Hall 4018, 700 N. Woodlawn Ave, Bloomington, IN 47408, USA
Phone: (812) 855-3256  Fax: -6166

**Comment by bherr2** [comment]
Ok, the build has been updated to show the proper version on about and sci2.ini is now the correct one. So, at this point 1.3 is officially released and on the sci2 website!

**Comment by bherr2** [comment]
@katyb announcements and release notes were already sent out, but feel free to announce to students too. Release notes are here: http://wiki.cns.iu.edu/display/SCI2TUTORIAL/4.7+Sci2+Release+Notes+v1.3
