### ISSUE TITLE
AggregationFunction Raises Exception in Extract Cooccurence Network

### ISSUE THREAD

**Issue by obscrivn** [CIShell/cishell-plugins#5]
Exception is raised after using properties files for Cooccurrence network:
```
node.numberOfWorks = Authors.count
node.firstPubYear = Year.min
node.timesCited = TC.sum
edge.numberOfCoAuthoredWorks = Authors.count
edge.firstPub = Year.min
```
*TC* column is general in all there files ai/iot/robotics and the content is as follows:
```Authors, Year, TC
"Flatt, R|Kirchberg, M|Link, S",2011,0
```
(files: https://iu.app.box.com/folder/72417799525)

- only ai was executed properly (cells format -general) 
- robotics and iot raised errors about string values in TC (cells format - general)

Note: co-occurrence extraction works for all three without a properties file  and  the Year column is treated as numeric (cells format - general)

- File type AI: ASCII text, with CRLF line terminators
- File Type Robotics: ASCII text, with very long lines, with CRLF line terminators
- File Type AI: ASCII text, with CRLF line terminators

**Comment by bherr2** [comment]
In working with @obscrivn we determined that that issue was with a malformed input file.
